### ISSUE TITLE
add support for other unsafe operations on IO (cats effect 3)

### ISSUE THREAD

**Issue by BusyByte** [wiringbits/wiringbits-scala-newbie-warts#1]
unsafeRunAsync
unsafeRunAsyncOutcome
unsafeRunAndForget
unsafeToFuture
unsafeToFutureCancelable
unsafeRunCancelable

maybe could define a Seq and define them all like the docs say for the built in warts like (Warts.unsafe)
Maybe something like :
`net.wiringbits.warts.CatsEffectWarts.unsafe` and the unsafe Seq would have the unsafeRunSync plus the others mentioned above.

**Comment by AlexITC** [comment]
Good idea.

Including those should be relatively similar to `unsafeRunSync`, would you be willing to submit a patch with another wart?

The reason why we only have `unsafeRunSync` right now is because that was something causing problems in one of the projects we work on.

**Comment by BusyByte** [comment]
We are just moving to CE3 and refactored out all our unsafe calls and I wanted to ensure it doesn't creep back in.  I'll work on adding the other Warts as mentioned above and submit a PR.

**Comment by AlexITC** [comment]
Released at https://github.com/wiringbits/wiringbits-scala-newbie-warts/releases/tag/v0.3.0, thanks!
