### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by BusyByte** [wiringbits/wiringbits-scala-newbie-warts#5]
Wart remover works on Scala 3 but I tried to download this custom wart for Scala 3 and it is not found.

@AlexITC can we add support for Scala 3?

**Comment by AlexITC** [comment]
Thanks for bringing this up, you are not the first one asking for Scala 3 support.

**Comment by BusyByte** [comment]
@AlexITC  I was thinking this might be a good time to also drop cats effect 2.x support if you are planning on a new developer minor version bump.  We have been on cats effect 3.x for everything for a while now.  Although this is not a requirement to support Scala 3 as there is a Scala 3 release for cats effect 2.x.  I just thought it might make implementing  Scala 3 release easier with less variables.

**Comment by AlexITC** [comment]
In fact, I asked one of our devs to handle this issue earlier by dropping scala 2 and cats-effect-2.

Thanks for the suggestion.

**Comment by BusyByte** [comment]
@AlexITC also was curious what version of Scala 3 would be targeted.  For internal libraries we've been targeting the [LTS Scala version 3.3 series](https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html).

**Comment by AlexITC** [comment]
Thanks for the hint, LTS is ideal.

**Comment by AlexITC** [comment]
Resolved by #6, release pending.

**Comment by AlexITC** [comment]
Released https://github.com/wiringbits/wiringbits-scala-newbie-warts/releases/tag/v0.4.2

**Comment by BusyByte** [comment]
@AlexITC  It looks like 0.4.1 was pushed to maven central [here](https://mvnrepository.com/artifact/net.wiringbits/cats-effect-warts_3/0.4.1).  Is that the right release to use?  Or should I hold off on a 0.4.2 release published?

**Comment by AlexITC** [comment]
Somehow the process messed up with the versions, when I created the release for 0.4.2, the process pushed 0.4.1 instead.

In any case, I have just pushed 0.4.3 which should be available in maven central.

In short, either 0.4.1 or 0.4.3 are ok, they are the same.

Thanks for sharing.
